<?php

namespace Siteadmin2Bundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Siteadmin2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Siteadmin2Repository extends EntityRepository
{
}
